# ==============================================================================
# INTEGRANTE B: Implementación de Videos 4 a 6 (Manipulación de Arrays)
# ==============================================================================

## Video 4: Listas vs Arrays en Numpy
* **Análisis visual:** Una lista de Python guarda diferentes tipos de datos y los almacena en distintos lugares de la memoria, lo que la hace lenta. Un array de Numpy guarda un solo tipo de dato en bloques de memoria continuos, haciéndolo mucho más rápido y eficiente para cálculos matemáticos.

## Video 5 y 6: Creación de Arrays y Funciones Básicas
* **Análisis visual:** Para usar las funciones matemáticas de Numpy, primero debemos convertir nuestras listas normales a arreglos de Numpy usando `np.array()`. Una vez convertidos, podemos usar funciones nativas como `type()` para verificar el tipo de objeto, o generar datos automáticos sin tener que escribirlos uno por uno.

In [3]:
import numpy as np

# ------------------------------------------------------------------------------
# 1. CONVERSIÓN DE LISTA A ARRAY (Video 5)
# ------------------------------------------------------------------------------
# Lógica: Tomamos una lista estándar de Python y la transformamos en un objeto de Numpy
lista_python = [10, 20, 30, 40, 50]
mi_primer_array = np.array(lista_python)

print("Impresión de la lista normal:", lista_python)
print("Impresión del Array de Numpy:", mi_primer_array)
# Nota visual: El array se imprime sin comas entre los números.

# ------------------------------------------------------------------------------
# 2. VERIFICACIÓN DE TIPO (Video 6)
# ------------------------------------------------------------------------------
# Lógica: Usamos type() para confirmar que el objeto dejó de ser una lista (list) 
# y ahora es un arreglo n-dimensional de Numpy (numpy.ndarray)
print("\nEl tipo de dato de la lista es:", type(lista_python))
print("El tipo de dato del array es:", type(mi_primer_array))

# ------------------------------------------------------------------------------
# 3. CREACIÓN DIRECTA DE ARRAYS MULTIDIMENSIONALES
# ------------------------------------------------------------------------------
# Lógica: Podemos crear matrices (arrays de 2 dimensiones) pasando listas dentro de una lista
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatriz de 2 dimensiones:\n", matriz)

Impresión de la lista normal: [10, 20, 30, 40, 50]
Impresión del Array de Numpy: [10 20 30 40 50]

El tipo de dato de la lista es: <class 'list'>
El tipo de dato del array es: <class 'numpy.ndarray'>

Matriz de 2 dimensiones:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
