# ==============================================================================
# INTEGRANTE C: Implementación de Videos 7 a 9 (Generación y Atributos)
# ==============================================================================

## Video 7 y 8: Generación automática de Arrays
* **Análisis visual:** En lugar de escribir listas a mano, Numpy tiene funciones como `arange()` para crear secuencias numéricas, `zeros()` para crear matrices vacías (llenas de ceros), y funciones de `random` para generar datos al azar. Esto es súper útil para inicializar datos en Machine Learning.

## Video 9: Atributos y Cambio de Forma (Reshape)
* **Análisis visual:** Los arrays tienen propiedades internas (atributos) que nos dicen su tamaño y dimensiones sin tener que usar funciones externas. Además, con `.reshape()` podemos tomar una línea plana de números y doblarla para convertirla en una matriz de 2 o 3 dimensiones, siempre y cuando los elementos encajen perfectamente.

In [1]:
import numpy as np

# ------------------------------------------------------------------------------
# 1. GENERACIÓN AUTOMÁTICA DE DATOS (Videos 7 y 8)
# ------------------------------------------------------------------------------
# Lógica: np.arange(inicio, fin, salto) funciona igual que range() de Python pero genera un array
secuencia_pares = np.arange(0, 11, 2)
print("Secuencia de números pares:", secuencia_pares)

# Lógica: np.zeros y np.ones crean arreglos llenos de 0s o 1s (útil para inicializar redes neuronales)
arreglo_ceros = np.zeros(4)
print("Arreglo de ceros:", arreglo_ceros)

# Lógica: np.random.randint(inicio, fin, cantidad) genera números enteros al azar
numeros_aleatorios = np.random.randint(1, 100, 5)
print("Números aleatorios del 1 al 100:", numeros_aleatorios)

# ------------------------------------------------------------------------------
# 2. ATRIBUTOS Y CAMBIO DE FORMA - RESHAPE (Video 9)
# ------------------------------------------------------------------------------
# Lógica: Creamos un array lineal de 9 elementos (del 1 al 9)
array_lineal = np.arange(1, 10)

# Lógica: Usamos .reshape(filas, columnas) para transformarlo en una matriz de 3x3
matriz_3x3 = array_lineal.reshape(3, 3)
print("\nMatriz transformada con reshape:\n", matriz_3x3)

# Lógica: Comprobamos los atributos nativos del array (.ndim para dimensiones, .shape para la forma)
print("\nDimensiones de la matriz:", matriz_3x3.ndim)
print("Forma exacta de la matriz:", matriz_3x3.shape) # Devuelve (3, 3)

Secuencia de números pares: [ 0  2  4  6  8 10]
Arreglo de ceros: [0. 0. 0. 0.]
Números aleatorios del 1 al 100: [71 51 15 70 18]

Matriz transformada con reshape:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Dimensiones de la matriz: 2
Forma exacta de la matriz: (3, 3)
